# Generated by Django 2.1.2 on 2018-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181015_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://i.imgur.com/4kKLl9G.png', max_length=200),
        ),
    ]
