# Generated by Django 2.1.2 on 2018-10-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='user',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='L', max_length=2),
        ),
    ]
