# Generated by Django 2.1.2 on 2018-10-18 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181017_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 18)),
        ),
    ]
